[package]
name = "jaogregori/dzienniczekxd"
version = "0.1.0"
description = "Moja aplikacja PHP"

# Tutaj mówimy Wasmerowi, żeby pobrał gotowy kontener PHP z ich bazy
[dependencies]
"php/php" = "8.2"

[[command]]
name = "run"
module = "php/php:php"
runner = "https://webc.org/packages/php/php"

[http_server]
kind = "cgi"
module = "php/php:php"
